"""Vehicle alerts — active and historical notifications.

Alerts are generated by the system (health, maintenance, behaviour,
insurance, inspection) and surfaced to the user via the Dashboard and
the agent.  Each alert has a lifecycle: active → acknowledged → resolved.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base


class VehicleAlert(Base):
    """A single alert attached to a vehicle."""

    __tablename__ = "vehicle_alerts"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    vehicle_id: Mapped[int] = mapped_column(
        ForeignKey("vehicles.id", ondelete="CASCADE"), index=True
    )

    # maintenance | health | behavior | insurance | inspection | system
    alert_type: Mapped[str] = mapped_column(String(32), index=True)
    # info | warning | critical
    level: Mapped[str] = mapped_column(String(16), index=True)
    category: Mapped[str | None] = mapped_column(String(64), nullable=True)

    title: Mapped[str] = mapped_column(String(128))
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    recommendation: Mapped[str | None] = mapped_column(Text, nullable=True)

    # active | acknowledged | resolved
    status: Mapped[str] = mapped_column(String(16), default="active", index=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime, nullable=True
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    triggered_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), index=True
    )
