"""Data models for the memory engine.

The core abstraction is the :class:`VehicleMemory`: a single
**event → impact** record.  Each memory links *what happened* (the event)
to *what it affected* (the impact), creating a semantic layer that goes
beyond raw telemetry logs.

Schema (mirrors the SQL table ``vehicle_memories``)::

    vehicle_memories(
      id              TEXT PRIMARY KEY,
      vehicle_id      TEXT NOT NULL,
      occurred_at     TEXT NOT NULL,      -- ISO-8601 timestamp
      event_type      TEXT NOT NULL,      -- what happened
      payload         TEXT,               -- JSON event details
      impact_target   TEXT,               -- what was affected (e.g. "battery_stress")
      impact_delta    REAL,               -- impact magnitude (e.g. +0.3)
      confidence      REAL,               -- 0.0-1.0
      source          TEXT NOT NULL,      -- "simulator" | "diagnosis" | "user" | "agent"
      created_at      TEXT NOT NULL       -- ISO-8601 timestamp
    )
"""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4


class Source(str, Enum):
    """Where a memory originated.

    Attributes
    ----------
    SIMULATOR : str
        Generated by the virtual-vehicle simulator during a lifecycle run.
    DIAGNOSIS : str
        Produced by a diagnosis agent during a consultation.
    USER : str
        Reported by the vehicle owner (e.g. "I heard a strange noise").
    AGENT : str
        Synthesised by any other agent (guardian, safety, value, etc.).
    """

    SIMULATOR = "simulator"
    DIAGNOSIS = "diagnosis"
    USER = "user"
    AGENT = "agent"


@dataclass(frozen=True)
class VehicleMemory:
    """A single persistent vehicle memory record.

    The fundamental unit of the memory engine: an event that occurred
    during a vehicle's lifecycle, linked to the impact it had on a
    vehicle component or metric.

    Attributes
    ----------
    id : str
        Unique record ID (UUID hex).
    vehicle_id : str
        The vehicle this memory belongs to (typically a VIN).
    occurred_at : datetime
        When the event *happened* (not when it was recorded).
    event_type : str
        What happened — e.g. ``"fast_charge_session"``,
        ``"cooling_fault"``, ``"maintenance"``, ``"diagnosis"``.
    payload : dict
        Event details as a JSON-serialisable dict (e.g.
        ``{"ratio": 0.8, "duration_min": 35}``).
    impact_target : str | None
        What the event *impacted* — e.g. ``"battery_stress"``,
        ``"motor_wear"``, ``"brake_safety"``.  ``None`` if the event
        has no direct component impact (e.g. a user chat).
    impact_delta : float
        The signed magnitude of the impact.  Positive = degradation
        (e.g. ``+0.3`` stress), negative = improvement (e.g. ``-0.1``
        after maintenance).
    confidence : float
        How confident the source is about the impact link (0.0-1.0).
    source : str
        Where the memory came from (see :class:`Source`).
    created_at : datetime
        When the memory was *recorded* in the engine.
    """

    id: str
    vehicle_id: str
    occurred_at: datetime
    event_type: str
    payload: dict[str, Any] = field(default_factory=dict)
    impact_target: str | None = None
    impact_delta: float = 0.0
    confidence: float = 1.0
    source: str = Source.AGENT.value
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dictionary."""
        d = asdict(self)
        d["occurred_at"] = self.occurred_at.isoformat()
        d["created_at"] = self.created_at.isoformat()
        return d

    def to_db_row(self) -> tuple:
        """Serialise to a SQLite row tuple (column order matches the schema)."""
        return (
            self.id,
            self.vehicle_id,
            self.occurred_at.isoformat(),
            self.event_type,
            json.dumps(self.payload, ensure_ascii=False),
            self.impact_target,
            self.impact_delta,
            self.confidence,
            self.source,
            self.created_at.isoformat(),
        )

    @classmethod
    def from_db_row(cls, row: tuple) -> VehicleMemory:
        """Deserialise from a SQLite row tuple."""
        (
            _id,
            vehicle_id,
            occurred_at_str,
            event_type,
            payload_str,
            impact_target,
            impact_delta,
            confidence,
            source,
            created_at_str,
        ) = row
        return cls(
            id=_id,
            vehicle_id=vehicle_id,
            occurred_at=datetime.fromisoformat(occurred_at_str),
            event_type=event_type,
            payload=json.loads(payload_str) if payload_str else {},
            impact_target=impact_target,
            impact_delta=impact_delta,
            confidence=confidence,
            source=source,
            created_at=datetime.fromisoformat(created_at_str),
        )

    @classmethod
    def create(
        cls,
        vehicle_id: str,
        event_type: str,
        occurred_at: datetime | None = None,
        payload: dict[str, Any] | None = None,
        impact_target: str | None = None,
        impact_delta: float = 0.0,
        confidence: float = 1.0,
        source: str | Source = Source.AGENT,
    ) -> VehicleMemory:
        """Factory with sensible defaults (auto-generates id and timestamps)."""
        if isinstance(source, Source):
            source = source.value
        return cls(
            id=uuid4().hex,
            vehicle_id=vehicle_id,
            occurred_at=occurred_at or datetime.now(timezone.utc),
            event_type=event_type,
            payload=payload or {},
            impact_target=impact_target,
            impact_delta=impact_delta,
            confidence=confidence,
            source=source,
        )


@dataclass
class MemorySummary:
    """The output of :meth:`MemoryEngine.summarize_for_agent`.

    A token-budgeted natural-language summary of a vehicle's memory,
    ready for injection into an agent prompt.

    Attributes
    ----------
    vehicle_id : str
        The vehicle the summary covers.
    text : str
        The natural-language summary (Chinese, agent-ready).
    memory_count : int
        How many memory records were considered.
    topics : list[str]
        The distinct impact topics covered (e.g. ``["battery_stress",
        "brake_wear"]``).
    token_estimate : int
        Rough token count of ``text`` (≈ chars / 2 for Chinese).
    truncated : bool
        True if the summary was cut to fit the token budget.
    """

    vehicle_id: str
    text: str
    memory_count: int
    topics: list[str]
    token_estimate: int
    truncated: bool
